version: '3'
services:
  pyx:
    build: .
    command: tail -f /dev/null
    #command: /opt/tomcat/bin/catalina.sh run
    ports:
     - "8080:8080"
    volumes:
      - .pyx:/app
    environment:
      TOMCAT_USER: tomcat_user
      TOMCAT_PASSWORD: tomcat_password
      DB_NAME: pyx
      DB_USER: pyx
      DB_PASSWORD: CorrectHorseBatteryStaple
  postgres:
    image: "postgres:alpine"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pyx
      POSTGRES_USER: pyx
      POSTGRES_PASSWORD: CorrectHorseBatteryStaple
